config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :studios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root 'animes#index'
  resources :animes, :characters
  root "pages#home"

  get "animes", to: "animes#index"
  get "animes/:id", to: "animes#show" # , as: :animes
  get "animes/new", to: "animes#new"
  post "animes", to: "animes#create"
  get "animes/:id/edit", to: "animes#edit", as: :animes_edit
  patch "animes/:id", to: "animes#update"
  delete "animes/:id", to: "animes#destroy"

  get "characters/new", to: "characters#new"
  post "characters", to: "characters#create"
  get "characters/:id/edit", to: "characters#edit", as: :characters_edit
  patch "characters/:id", to: "characters#update"
  delete "characters/:id", to: "characters#destroy"

  get 'pages/allAnime'
  get 'pages/home'
  get 'pages/Movie'
  get 'pages/Series'


end

app/models/anime.rb
class Anime < ApplicationRecord
    has_and_belongs_to_many :characters, dependent: :destroy
    accepts_nested_attributes_for :characters,allow_destroy: true
    belongs_to :studio

    mount_uploader :image , ImageUploader

    validates :name,presence: true
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_and_belongs_to_many :animes
    mount_uploader :pic , PicUploader

    validates :name,presence: true  
    
end

app/models/studio.rb
class Studio < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :animes, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable  
  
  def studioname
    return self.email.split('@')[0].capitalize        
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
   before_action :authenticate_studio!, except:[:show, :index] 
  # before_action :check, only:[:index]
  
  def index
    @animes = Anime.where(studio_id: current_studio.id)
    #render json: @animes
      end
    
      def show
        @anime = Anime.find(params[:id])
        @characters = @anime.characters
      end

      def new
        @anime = Anime.new
      end
    
      def create    
        @anime = Anime.new(anime_params) 
        @anime.studio = current_studio
        @anime.save
        redirect_to @anime
      end
    

        def edit
            @anime = Anime.find(params[:id])
          end
    
          def update
            anime = Anime.find(params[:id])
            anime.update(anime_params)
              
            redirect_to animes_path
          end
    
          def destroy
            Anime.find(params[:id]).destroy
            redirect_to animes_path
          end  

      private
    
       def anime_params
         params.require(:anime).permit( :name, :category, :aired_year,
          :episodes, :duration,:studio_id,:image)
       end

      
      # def anime_params
      #   params.require(:anime).permit(:name, :category, :aired_year,
      #   :episodes, :duration,
      #   characters_attributes:[:id,:name, :birth_year, :gender,:_destroy])
      # end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_studio! 
  # def show
  #   @characters = Character.where(anime_id: anime_id.id)
  # end

    def new
        @anime = Anime.find(params[:anime_id])
        @character = Character.new
      end
    
      def create
          puts params
            @anime = Anime.find(params[:character][:anime_id])
            @anime.characters.create(character_params)
            redirect_to @anime
      end

      def edit
        @character = Character.find(params[:id])
      end

      def update
        @character = Character.find(params[:id])
        @character.update(character_params)
        redirect_to animes_path
      end

      def destroy
       Character.find(params[:id]).destroy
       redirect_to animes_path 
      end

      private
    
      def character_params
        params.require(:character).permit(:name, :birth_year, :gender, :pic)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # def home
  #     @animes = Anime.all
  # end
  def allAnime
    @animes = Anime.all
end
def Movie
  @animes = Anime.where(category: "Movie")
end
def Series
  @animes = Anime.where(category: "Series")
end
  
  
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/animes/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<title>Anime App</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="style.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
<div class="center">
<%= form_for@anime do |f| %>

  <p class="form-group">
    <%= f.label :name, "Anime name" %>
    <%= f.text_field :name %>
  </p>

  <p class="form-group">
    <%= f.label :Category, "Anime category" %>  
    <%= f.text_field :category %>
  </p>

  <p class="form-group">
    <%= f.label :aired_year, "Anime aired year" %>
    <%= f.number_field :aired_year %>
  </p>

  <p class="form-group">
    <%= f.label :episodes, "Anime episodes" %>
    <%= f.number_field :episodes %>
  </p>
  
  <p class="form-group">
    <%= f.label :duration, "Anime duration" %>
    <%= f.number_field :duration %>
  </p>
  
<p class="form-group">
    <%= f.label :image, "Anime poster" %>
    <%= f.file_field :image %>
  </p>

  <p class="form-group">
    <%= f.submit 'Submit' %>
  </p>
<% end %>

<%= link_to 'Back', animes_path %>
</div>


</body>
</html>

app/views/animes/index.html.erb
<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>
  <%= link_to "New anime", new_anime_path(:studio_id => @current_studio.id), { :class => "btn btn-primary btn-lg" } %>

<br><br>
<div class="row">

        <% current_studio.animes.each do |anime| %>
            <div class="col-xs-6 col-md-3">
                <div class="thumbnail">
        <p><%= link_to anime.name , anime_path(anime) %></p>
        <% if anime.image_url %>
            <%= link_to image_tag(anime.image_url , size: "250x300", alt: "Anime Image"), anime_path(anime)%>
        <% end %>
        </div>
        </div>
<% end %>
</div>

app/views/animes/new.html.erb
<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>
<h1>New Anime</h1>

<%= render 'animes/form' %>

app/views/animes/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>
	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>

<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>
	<title>Anime App</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>

<br><br>
<h1><%=@anime.name%> informations</h1>

<div class="row">
    <div class="col-xs-6 col-md-3">
<p>
<% if @anime.image_url %>
<%= image_tag @anime.image_url , size: "250x300", alt: "Anime Image", class:"thumbnail"%>
<% end %>
<% if current_studio %>
          <% if current_studio.id==@anime.studio.id %>
          <a class="glyphicon glyphicon-edit" href="<%= edit_anime_path(@anime) %>" > </a> 
          <a class="glyphicon glyphicon-trash" data-confirm="Are you sure you want to delete <%= @anime.name%>?" data-method="delete" href="/animes/<%= @anime.id %>" rel="nofollow"></a>
          <% end %>
<% end %>
</p>
    <div class="thumbnail">
      <p> Studio: <%= @anime.studio.studioname %></p>
      <p> Type: <%= @anime.category %></p>
      <p> Aired year: <%= @anime.aired_year %></p>
      <p> Duration: <%= @anime.duration %></p>
      <p> Episode: <%= @anime.episodes %></p> 
    </div>
  </div>
</div>

<h1><%= @anime.name %> characters</h1>


<% if current_studio %>
  <% if current_studio.id==@anime.studio.id %>
  <%= link_to "New Character", new_character_path(:anime_id => @anime.id), { :class => "btn btn-primary btn-lg" } %>
  <% end %>
<% end %>

<br><br>
<div class="row">

<% @characters.each do |character| %>
    <div class="col-xs-6 col-md-3">

<p>  

<% if character.pic_url %>
  <%= image_tag character.pic_url , size: "250x300", alt: "Character Picture", class:"thumbnail"%>
<% end %>

<% if current_studio %>
    <% if current_studio.id==@anime.studio.id %>
      <a class="glyphicon glyphicon-edit" href="<%= edit_character_path(character) %>" ></a> 
      <a class="glyphicon glyphicon-trash" data-confirm="Are you sure you want to delete <%= character.name %>?" data-method="delete" href="/characters/<%= character.id %>" rel="nofollow"></a>
    <% end %>
  <% end %>

</p>

<div class="thumbnail">
<p>Name: <%= character.name %></p>
<p>Gender: <%= character.gender %></p>
<p>Birth year: <%= character.birth_year %><p>
</div>   
</div>   

<% end %>
</div>   


</body>
</html>

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>


	<title>Anime App</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<!-- Header section -->
	<header class="header-section">
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
		<div class="header-warp">
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="/pages/home" class="site-logo">
					<img src="/assets/logo.png" alt="">
				</a>
      	<nav class="top-nav-area w-100">

<div class="user-panel">
  <% if studio_signed_in? %>
  <div style="color:white;">
      Logged in as  <strong ><%= current_studio.email %></strong>
  </div>
    <%= link_to 'Edit profile', edit_studio_registration_path %> / 
    <%= link_to "Sign out", destroy_studio_session_path, method: :delete %> /
    <%= link_to "Edit our animes", animes_path  %>

  <% else %>
    <%= link_to "Sign in", new_studio_session_path %> /
    <%= link_to "Sign up", new_studio_registration_path  %>
  <% end %>
</div>

					<!-- Menu -->
					<ul class="main-menu primary-menu">
						<li><%= link_to "Home" , href="/pages/home"%></li>
                       	<li><%= link_to "All anime" , href="/pages/allAnime"%></li>
						<li><%= link_to "Movies" , href="/pages/Movie"%></li>
						<li><%= link_to "Series" , href="/pages/Series"%></li>
					</ul>
				</nav>
			</div>
		</div>
    
	</header>
	<!-- Header section end -->
  </body>
</html>

app/views/pages/Movie.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>


	<title>Movie</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>

<div class="row">
  <% @animes.each do |anime| %>
    <div class="col-xs-6 col-md-3">
      <% if anime.category=="Movie" %>
        <p><%= anime.name %></p>
        <% if anime.image_url %>
        <%= link_to image_tag(anime.image_url , size: "250x300", alt: "Anime Image", class:"thumbnail"), anime_path(anime)%>
        <% end %> 
    <% end %>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/pages/Series.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>

	<title>Series</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>


<div class="row">
  <% @animes.each do |anime| %>
    <div class="col-xs-6 col-md-3">
      <% if anime.category=="Series" %>
        <p><%= anime.name %></p>
        <% if anime.image_url %>
        <%= link_to image_tag(anime.image_url , size: "250x300", alt: "Anime Image", class:"thumbnail"), anime_path(anime)%>
        <% end %> 
    <% end %>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/pages/allAnime.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>


	<title>Anime App</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
<br><br><br><br><br><br>
<br><br><br><br><br><br>
<br><br><br><br>
<div class="row">
  <% @animes.each do |anime| %>
    <div class="col-xs-6 col-md-3">
      <p><%= anime.name%></p>
      <% if anime.image_url %>
            <%= link_to image_tag(anime.image_url, size: "250x300", alt: "Anime Image", class:"thumbnail" ), anime_path(anime)%>
        <% end %>
    </div>
  <% end %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	<!--Custom styles-->
<%= stylesheet_link_tag "homeStyle.css" %>


	<title>Anime App</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<%= stylesheet_link_tag "bootstrap.min.css"%>
	<%= stylesheet_link_tag  "font-awesome.min.css"%>
	<%= stylesheet_link_tag "slicknav.min.css"%>
	<%= stylesheet_link_tag  "owl.carousel.min.css"%>
	<%= stylesheet_link_tag "magnific-popup.css"%>
	<%= stylesheet_link_tag "animate.css"%>

	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag href="homeStyle2.css"%>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>
<br><br><br>
<div class="container2">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item">
        <img src="/assets/1.jpg" alt="1" style="width:100%;">
      </div>

      <div class="item">
        <img src="/assets/2.jpg" alt="2" style="width:100%;">
      </div>
    
      <div class="item active">
        <img src="/assets/3.jpg" alt="3" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<br><br>

	<!-- Intro section -->
	<section class="intro-section">
		<div class="container">
			<div class="row">
				
        <div class="col-md-4">
					<div class="intro-text-box text-box text-white">
						<h3>Last Anime</h3>
              <% last_anime=Anime.last %>
              <% if !last_anime.nil? %>
                <% if last_anime.image_url %>
                <%= link_to image_tag(last_anime.image_url , size: "250x300", alt: "Anime Image"), anime_path(last_anime)%>
                <% end %> 
                <% end %> 
          </div>
				</div>
			</div>
		</div>
	</section>
	<!-- Intro section end -->

</body>
</html>